# traefik.toml

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]
address = "traefik.chell.rael.io:80"

[docker]
domain = "chell.rael.io"
watch = true

[file]
watch = true
filename = "/etc/traefik/chell-rules.toml"
